#!/usr/bin/env bash
# S3 e2e (docs/build-plan.md): local replica + local SOL RPC canister against
# the real Solana devnet splitter.
#
# Usage:
#   scripts/e2e-local.sh <donor-keypair> <recipient-pubkey> [gross]
# Env:
#   RPC_URL                 devnet RPC for the donate client (default public)
#   CROWN_PRIOR_SETTLEMENTS settlements already on-chain before this run, as
#                           "chain,donor,recipient,gross;..." — the recount and
#                           the reputation check need the full history.
#
# The donor keypair needs devnet SOL and USDC. Steps:
#   1. deploy sol_rpc + crown-index (pinned to the local sol_rpc; the cursor
#      is seeded at the splitter's latest signature, so the book starts empty),
#   2. donate once through the devnet splitter,
#   3. ring ingest_hint and assert the record lands fast while the watchdog
#      is cranked far out — the hint, not the timer, must drive the ingest,
#   4. assert reputation, exactly-once under repeated rings, zero anomalies,
#   5. verify the certificate offchain against the replica root key, and
#      the witness of one entry against the certified book root.
#
# THE LOCAL REPLICA IS SHARED AND IS NEVER WIPED HERE: game canisters on it
# hold threshold keys that resolve live devnet escrows. Only the core's own
# canisters are recreated — crown-index holds no keys and its book is
# derived state, safe to discard by design (core-spec §9).
set -euo pipefail
cd "$(dirname "$0")/.."

DONOR=${1:?donor keypair path}
RECIPIENT=${2:?recipient pubkey}
GROSS=${3:-1000000}
RPC_URL=${RPC_URL:-https://api.devnet.solana.com}
CHAIN_ID="solana-devnet"

export CC_wasm32_unknown_unknown="$PWD/scripts/wasm-cc.sh"
export AR_wasm32_unknown_unknown="${AR_WASM32:-$(command -v llvm-ar || ls -d "$HOME"/.cache/solana/*/platform-tools/llvm/bin/llvm-ar 2>/dev/null | sort -V | tail -1 | grep . || echo "$HOME/.cache/zig/zig-ar")}"

# The locally deployed SOL RPC canister has no provider API keys, so Default
# sources are unusable here. Build the index against a generated throwaway
# profile with a Custom public endpoint — allowed outside mainnet. The
# committed testnet/mainnet profiles stay untouched.
export CROWN_PROFILE=local
SPLITTER=$(grep '^splitter' config/testnet.toml | cut -d'"' -f2)
USDC=$(grep '^usdc' config/testnet.toml | cut -d'"' -f2)
cat > config/local.toml <<EOF
# Generated by scripts/e2e-local.sh for the local run; never committed.
# The watchdog is cranked far out on purpose: a fast record proves the hint.
ingest_watchdog = 900

[[chain]]
id        = "$CHAIN_ID"
source    = "Custom:$RPC_URL"
consensus = "equality"
splitter  = "$SPLITTER"
usdc      = "$USDC"
EOF

DONOR_PUBKEY=$(solana-keygen pubkey "$DONOR")

blob() { # base58 -> candid blob literal
    python3 - "$1" <<'EOF'
import sys
A = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"
s = sys.argv[1]
n = 0
for c in s:
    n = n * 58 + A.index(c)
b = n.to_bytes((n.bit_length() + 7) // 8, "big")
b = b"\0" * (len(s) - len(s.lstrip("1"))) + b
print("".join(f"\\{x:02x}" for x in b))
EOF
}

reputation() {
    dfx canister call crown-index get_reputation \
        "(\"$CHAIN_ID\", blob \"$(blob "$DONOR_PUBKEY")\", blob \"$(blob "$RECIPIENT")\")" \
        --query | tr -d '(_ )' | sed 's/:nat//'
}

if ! dfx ping >/dev/null 2>&1; then
    dfx start --background >/dev/null 2>&1
    for _ in $(seq 1 30); do dfx ping >/dev/null 2>&1 && break; sleep 1; done
fi
dfx ping >/dev/null 2>&1 || { echo "FAIL: replica did not come up" >&2; exit 1; }
# Fresh book and cursor every run; these canisters hold no keys.
dfx canister stop crown-index >/dev/null 2>&1 || true
dfx canister delete crown-index --yes >/dev/null 2>&1 || true
dfx canister stop sol_rpc >/dev/null 2>&1 || true
dfx canister delete sol_rpc --yes >/dev/null 2>&1 || true

SOL_SEED=$(curl -s "$RPC_URL" -X POST -H "Content-Type: application/json" -d "{
    \"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"getSignaturesForAddress\",
    \"params\":[\"$SPLITTER\", {\"limit\": 1}]}" \
    | python3 -c "import json,sys; print(json.load(sys.stdin)['result'][0]['signature'])")
echo "cursor seed: $SOL_SEED"

dfx deploy sol_rpc
SOL_RPC_ID=$(dfx canister id sol_rpc)
dfx deploy crown-index --argument "(opt record { sol_rpc = opt principal \"$SOL_RPC_ID\";
    cursor_seed = opt vec { record { \"$CHAIN_ID\"; \"$SOL_SEED\" } } })"
INDEX_ID=$(dfx canister id crown-index)
dfx ledger fabricate-cycles --canister crown-index --t 100 >/dev/null

echo "== donate $GROSS through the devnet splitter"
SIGNATURE=$(cargo run --manifest-path contracts/solana/Cargo.toml -q --example donate -- \
    "$RPC_URL" "$DONOR" "$RECIPIENT" "$GROSS")
echo "donate: $SIGNATURE"

EXPECTED_PAIR=$GROSS
HISTORY="${CROWN_PRIOR_SETTLEMENTS:-}"
for entry in ${HISTORY//;/ }; do
    case "$entry" in
        "$CHAIN_ID,$DONOR_PUBKEY,$RECIPIENT,"*) EXPECTED_PAIR=$((EXPECTED_PAIR + ${entry##*,})) ;;
    esac
done
HISTORY="${HISTORY:+$HISTORY;}$CHAIN_ID,$DONOR_PUBKEY,$RECIPIENT,$GROSS"

echo "== ring the alarm clock: the hint, not the 900s watchdog, drives ingest"
HINT_STARTED=$(date +%s)
GOT=""
for _ in $(seq 1 16); do
    dfx canister call crown-index ingest_hint '()' >/dev/null
    sleep 15
    GOT=$(reputation)
    echo "reputation($DONOR_PUBKEY -> $RECIPIENT) = $GOT / $EXPECTED_PAIR"
    [ "$GOT" = "$EXPECTED_PAIR" ] && break
done
[ "$GOT" = "$EXPECTED_PAIR" ] || { echo "FAIL: reputation never reached $EXPECTED_PAIR"; exit 1; }
ELAPSED=$(($(date +%s) - HINT_STARTED))
[ "$ELAPSED" -lt 600 ] || { echo "FAIL: the record took ${ELAPSED}s — watchdog, not hint"; exit 1; }
echo "the hint delivered the record in ${ELAPSED}s"

echo "== exactly-once: repeated rings must change nothing"
dfx canister call crown-index ingest_hint '()' >/dev/null
sleep 70
dfx canister call crown-index ingest_hint '()' >/dev/null
sleep 20
GOT=$(reputation)
[ "$GOT" = "$EXPECTED_PAIR" ] || { echo "FAIL: book changed on idle rings: $GOT"; exit 1; }

echo "== anomalies must be zero"
ANOMALIES=$(dfx canister call crown-index get_anomaly_count --query | tr -d '(_ )' | sed 's/:nat64//')
[ "$ANOMALIES" = "0" ] || { echo "FAIL: anomaly count = $ANOMALIES"; exit 1; }

echo "== reduce version"
dfx canister call crown-index get_reduce_version --query

echo "== offchain certificate + witness verification against the replica root key"
CROWN_REPLICA_URL="http://127.0.0.1:$(dfx info webserver-port)" \
CROWN_INDEX_ID="$INDEX_ID" \
CROWN_E2E_SETTLEMENTS="$HISTORY" \
    cargo test -p crown-index --test certificate -- --ignored --nocapture

echo "e2e OK"
