#!/usr/bin/env bash
# Attribution e2e: recognition root no.2 against live devnet, both convention
# shapes (payout-table and stream). No new transactions: a table claim (2
# recipients, 70/30) and two stream releases already sit on chain.
#   - every escrow Settled lands in the book under the DONOR, one pair per
#     recipient;
#   - several Settled from one transaction are all counted;
#   - zero anomalies; the certificate agrees with an independent recount.
#
# Usage: scripts/e2e-attribution.sh
set -euo pipefail
cd "$(dirname "$0")/.."

SOL_RPC_URL=${SOL_RPC_URL:-https://api.devnet.solana.com}

# The constellation from the crown-factory drivers' `flow` runs
# (examples/devnet.rs, 2026-07-15): a payout-table claim = 2 Settled in one
# transaction (66500 -> A, 28500 -> B, net of the escrow's 5% fee); two
# stream releases add a pair each.
SOL_DONOR=2b6JQquqQDsS8o3DFDiaxFLKTFMro1YrvVq7aimV4FzD
SOL_STREAMER_A=Gt381v8RqGQUX7vdRbC9NdZCzGuzk6ZUgcTDLfUnYdcJ
SOL_STREAMER_B=ByQ5SXVFXM1zJRg5vDztqs4ZdRdRSSBgvoWvMAw5Rgcx
SOL_GOAL_A=199500   # 3 x 66500
SOL_GOAL_B=85500    # 3 x 28500
# The constellation's first transaction in the splitter history is the
# payout-table claim.
SOL_SETTLE_TX=1VbUq7uwn5yTP5MYdkx6sd6QozKFmszND4dH3b8hc5MdBT5cGFYfQdjiQdCSfgXxzVtGiZWgQmAgyAJBe4DuBjW

export CC_wasm32_unknown_unknown="$PWD/scripts/wasm-cc.sh"
export AR_wasm32_unknown_unknown="${AR_WASM32:-$HOME/.cache/solana/v1.53/platform-tools/llvm/bin/llvm-ar}"
export CROWN_PROFILE=local

chain_value() { grep "^$1" config/testnet.toml | sed -n "$2p" | cut -d'=' -f2- | tr -d ' "[]'; }
SOL_SPLITTER=$(chain_value splitter 1)
SOL_USDC=$(chain_value usdc 1)
# All pinned factories of the profile, back into TOML list syntax.
SOL_FACTORIES=$(chain_value factories 1 | sed 's/,/", "/g')

# Cursor seed: the splitter signature directly BEFORE the constellation's
# first transaction in history (ingest takes everything newer than it -
# exactly three transactions, six Settled).
SOL_SEED=$(curl -s "$SOL_RPC_URL" -X POST -H "Content-Type: application/json" -d "{
    \"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"getSignaturesForAddress\",
    \"params\":[\"$SOL_SPLITTER\", {\"limit\": 100}]}" | python3 -c "
import json, sys
sigs = [s['signature'] for s in json.load(sys.stdin)['result']]
print(sigs[sigs.index('$SOL_SETTLE_TX') + 1])")
echo "solana cursor seed: $SOL_SEED"

cat > config/local.toml <<EOF
# Generated by scripts/e2e-attribution.sh for the local run; never committed.
[[chain]]
id        = "solana-devnet"
source    = "Custom:$SOL_RPC_URL"
consensus = "equality"
splitter  = "$SOL_SPLITTER"
usdc      = "$SOL_USDC"
factories = ["$SOL_FACTORIES"]
EOF

echo "== canisters"
dfx stop >/dev/null 2>&1 || true
dfx start --clean --background
trap 'dfx stop >/dev/null 2>&1 || true' EXIT
dfx deploy sol_rpc
dfx deploy crown-index --argument "(opt record {
    sol_rpc = opt principal \"$(dfx canister id sol_rpc)\";
    cursor_seed = opt vec {
        record { \"solana-devnet\"; \"$SOL_SEED\" };
    } })"
INDEX_ID=$(dfx canister id crown-index)
dfx ledger fabricate-cycles --canister crown-index --t 100 >/dev/null

blob_b58() {
    python3 - "$1" <<'EOF'
import sys
A = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"
s = sys.argv[1]
n = 0
for c in s:
    n = n * 58 + A.index(c)
b = n.to_bytes((n.bit_length() + 7) // 8, "big")
b = b"\0" * (len(s) - len(s.lstrip("1"))) + b
print("".join(f"\\{x:02x}" for x in b))
EOF
}
reputation() { # payer_blob streamer_blob
    dfx canister call crown-index get_reputation "(\"solana-devnet\", blob \"$1\", blob \"$2\")" \
        --query | tr -d '(_ )' | sed 's/:nat//'
}

echo "== wait for ingest"
SOL_GOT_A=""
SOL_GOT_B=""
# Reputation queries are free local-replica reads, so poll finely (same ~500s
# ceiling) instead of in coarse 20s steps.
for _ in $(seq 1 100); do
    sleep 5
    SOL_GOT_A=$(reputation "$(blob_b58 $SOL_DONOR)" "$(blob_b58 $SOL_STREAMER_A)")
    SOL_GOT_B=$(reputation "$(blob_b58 $SOL_DONOR)" "$(blob_b58 $SOL_STREAMER_B)")
    echo "donor: A = $SOL_GOT_A / $SOL_GOAL_A, B = $SOL_GOT_B / $SOL_GOAL_B"
    [ "$SOL_GOT_A" = "$SOL_GOAL_A" ] && [ "$SOL_GOT_B" = "$SOL_GOAL_B" ] && break
done
[ "$SOL_GOT_A" = "$SOL_GOAL_A" ] && [ "$SOL_GOT_B" = "$SOL_GOAL_B" ] \
    || { echo "FAIL: settlements not attributed to donor"; exit 1; }

echo "== anomalies must be zero"
ANOMALIES=$(dfx canister call crown-index get_anomaly_count --query | tr -d '(_ )' | sed 's/:nat64//')
[ "$ANOMALIES" = "0" ] || { echo "FAIL: anomaly count = $ANOMALIES"; exit 1; }

echo "== certificate against the replica root key + independent recount"
CROWN_REPLICA_URL="http://127.0.0.1:$(dfx info webserver-port)" \
CROWN_INDEX_ID="$INDEX_ID" \
CROWN_E2E_SETTLEMENTS="solana-devnet,$SOL_DONOR,$SOL_STREAMER_A,$SOL_GOAL_A;solana-devnet,$SOL_DONOR,$SOL_STREAMER_B,$SOL_GOAL_B" \
    cargo test -p crown-index --test certificate -- --ignored --nocapture

echo "e2e attribution OK"
