#!/usr/bin/env bash
# S4 e2e (docs/build-plan.md): local replica + local EVM RPC canister against
# the REAL Ethereum Sepolia splitter from config/testnet.toml.
#
# Usage: PRIVATE_KEY=0x... scripts/e2e-evm-sepolia.sh [gross]
# The key's address needs Sepolia ETH (gas) and Sepolia USDC (the donate).
#
# Mind the clock: Ethereum finality lags ~13 minutes, and the first ingest
# catches up from genesis in ~10k-block chunks, so the run takes about an hour.
set -euo pipefail
cd "$(dirname "$0")/.."

GROSS=${1:-1000000}
CHAIN_ID="eth-sepolia"
RPC=${RPC:-https://sepolia.gateway.tenderly.co}
: "${PRIVATE_KEY:?set PRIVATE_KEY (see ~/.cache/crown-e2e/evm-deployer.key)}"

export CC_wasm32_unknown_unknown="$PWD/scripts/wasm-cc.sh"
export AR_wasm32_unknown_unknown="${AR_WASM32:-$HOME/.cache/solana/v1.53/platform-tools/llvm/bin/llvm-ar}"
export CROWN_PROFILE=local

value_of() { grep "^$1" config/testnet.toml | grep -o '"[^"]*"' | tr -d '"' | sed -n "$2p"; }
SPLITTER=$(value_of splitter 2)
USDC=$(value_of usdc 2)
DONOR=$(cast wallet address "$PRIVATE_KEY")
STREAMER=$(cast wallet new --json | python3 -c "import json,sys; print(json.load(sys.stdin)[0]['address'])")
echo "splitter: $SPLITTER  donor: $DONOR  streamer: $STREAMER"

cat > config/local.toml <<EOF
# Generated by scripts/e2e-evm-sepolia.sh for the local run; never committed.
[[chain]]
id        = "$CHAIN_ID"
source    = "Custom:11155111:$RPC"
consensus = "equality"
splitter  = "$SPLITTER"
usdc      = "$USDC"
EOF

# Seed the ingest cursor just below the donate: scanning a public chain from
# genesis in the EVM RPC canister's 500-block chunks would take many hours.
SEED=$(($(cast block finalized --rpc-url "$RPC" --field number) - 10))
echo "cursor seed: $SEED"

echo "== donate $GROSS on Sepolia (finality will take ~13 min)"
cast send --rpc-url "$RPC" --private-key "$PRIVATE_KEY" "$USDC" \
    "approve(address,uint256)" "$SPLITTER" "$GROSS" >/dev/null
DONATE_TX=$(cast send --rpc-url "$RPC" --private-key "$PRIVATE_KEY" "$SPLITTER" \
    "donate(address,uint256)" "$STREAMER" "$GROSS" --json | python3 -c "import json,sys; print(json.load(sys.stdin)['transactionHash'])")
echo "donate: $DONATE_TX"

echo "== canisters"
dfx stop >/dev/null 2>&1 || true
dfx start --clean --background
trap 'dfx stop >/dev/null 2>&1 || true' EXIT
dfx deploy evm_rpc
dfx deploy crown-index --argument \
    "(opt record { sol_rpc = null; evm_rpc = opt principal \"$(dfx canister id evm_rpc)\"; cursor_seed = opt vec { record { \"$CHAIN_ID\"; \"$SEED\" } } })"
INDEX_ID=$(dfx canister id crown-index)
dfx ledger fabricate-cycles --canister crown-index --t 100 >/dev/null

blob() { # 0x-hex -> candid blob escapes
    python3 -c "import sys; print(''.join(f'\\\\{b:02x}' for b in bytes.fromhex(sys.argv[1][2:])))" "$1"
}
reputation() {
    dfx canister call crown-index get_reputation \
        "(\"$CHAIN_ID\", blob \"$(blob "$DONOR")\", blob \"$(blob "$STREAMER")\")" \
        --query | tr -d '(_ )' | sed 's/:nat//'
}

echo "== wait for catch-up from genesis + finality (up to ~90 min)"
GOT=""
for _ in $(seq 1 90); do
    sleep 60
    GOT=$(reputation)
    CURSOR=$(dfx canister call crown-index get_cursor "(\"$CHAIN_ID\")" --query | tr -d '\n' || true)
    echo "reputation = $GOT / $GROSS   cursor: $CURSOR"
    [ "$GOT" = "$GROSS" ] && break
done
[ "$GOT" = "$GROSS" ] || { echo "FAIL: reputation never reached $GROSS"; exit 1; }

echo "== exactly-once: two more timer rounds must change nothing"
sleep 130
GOT=$(reputation)
[ "$GOT" = "$GROSS" ] || { echo "FAIL: book changed on idle rounds: $GOT"; exit 1; }

echo "== anomalies must be zero"
ANOMALIES=$(dfx canister call crown-index get_anomaly_count --query | tr -d '(_ )' | sed 's/:nat64//')
[ "$ANOMALIES" = "0" ] || { echo "FAIL: anomaly count = $ANOMALIES"; exit 1; }

echo "== offchain certificate verification against the replica root key"
CROWN_REPLICA_URL="http://127.0.0.1:$(dfx info webserver-port)" \
CROWN_INDEX_ID="$INDEX_ID" \
CROWN_E2E_SETTLEMENTS="$CHAIN_ID,$DONOR,$STREAMER,$GROSS" \
    cargo test -p crown-index --test certificate -- --ignored --nocapture

echo "e2e OK"
