#!/usr/bin/env bash
# S3 e2e (docs/build-plan.md): local replica + local SOL RPC canister against
# the real Solana devnet splitter.
#
# Usage:
#   scripts/e2e-local.sh <donor-keypair> <streamer-pubkey> [gross]
# Env:
#   RPC_URL                 devnet RPC for the donate client (default public)
#   CROWN_PRIOR_SETTLEMENTS settlements already on-chain before this run, as
#                           "chain,payer,streamer,gross;..." — the recount and
#                           the reputation check need the full history.
#
# The donor keypair needs devnet SOL and USDC. Steps:
#   1. deploy sol_rpc + crown-index (pinned to the local sol_rpc),
#   2. donate once through the devnet splitter,
#   3. wait for the ingest timer to fold the whole history into the book,
#   4. assert reputation, exactly-once, zero anomalies,
#   5. verify the certificate offchain against the replica root key.
set -euo pipefail
cd "$(dirname "$0")/.."

DONOR=${1:?donor keypair path}
STREAMER=${2:?streamer pubkey}
GROSS=${3:-1000000}
RPC_URL=${RPC_URL:-https://api.devnet.solana.com}
CHAIN_ID="solana-devnet"

export CC_wasm32_unknown_unknown="$PWD/scripts/wasm-cc.sh"
export AR_wasm32_unknown_unknown="${AR_WASM32:-$HOME/.cache/solana/v1.53/platform-tools/llvm/bin/llvm-ar}"

# The locally deployed SOL RPC canister has no provider API keys, so Default
# sources are unusable here. Build the index against a generated throwaway
# profile with a Custom public endpoint — allowed outside mainnet. The
# committed testnet/mainnet profiles stay untouched.
export CROWN_PROFILE=local
SPLITTER=$(grep '^splitter' config/testnet.toml | cut -d'"' -f2)
USDC=$(grep '^usdc' config/testnet.toml | cut -d'"' -f2)
cat > config/local.toml <<EOF
# Generated by scripts/e2e-local.sh for the local run; never committed.
[[chain]]
id        = "$CHAIN_ID"
source    = "Custom:$RPC_URL"
consensus = "equality"
splitter  = "$SPLITTER"
usdc      = "$USDC"
EOF

DONOR_PUBKEY=$(solana-keygen pubkey "$DONOR")

blob() { # base58 -> candid blob literal
    python3 - "$1" <<'EOF'
import sys
A = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"
s = sys.argv[1]
n = 0
for c in s:
    n = n * 58 + A.index(c)
b = n.to_bytes((n.bit_length() + 7) // 8, "big")
b = b"\0" * (len(s) - len(s.lstrip("1"))) + b
print("".join(f"\\{x:02x}" for x in b))
EOF
}

reputation() {
    dfx canister call crown-index get_reputation \
        "(\"$CHAIN_ID\", blob \"$(blob "$DONOR_PUBKEY")\", blob \"$(blob "$STREAMER")\")" \
        --query | tr -d '(_ )' | sed 's/:nat//'
}

dfx stop >/dev/null 2>&1 || true
dfx start --clean --background
trap 'dfx stop >/dev/null 2>&1 || true' EXIT

dfx deploy sol_rpc
SOL_RPC_ID=$(dfx canister id sol_rpc)
dfx deploy crown-index --argument "(opt principal \"$SOL_RPC_ID\")"
INDEX_ID=$(dfx canister id crown-index)
dfx ledger fabricate-cycles --canister crown-index --t 100 >/dev/null

echo "== donate $GROSS through the devnet splitter"
SIGNATURE=$(cargo run --manifest-path contracts/solana/Cargo.toml -q --example donate -- \
    "$RPC_URL" "$DONOR" "$STREAMER" "$GROSS")
echo "donate: $SIGNATURE"

EXPECTED_PAIR=$GROSS
HISTORY="${CROWN_PRIOR_SETTLEMENTS:-}"
for entry in ${HISTORY//;/ }; do
    case "$entry" in
        "$CHAIN_ID,$DONOR_PUBKEY,$STREAMER,"*) EXPECTED_PAIR=$((EXPECTED_PAIR + ${entry##*,})) ;;
    esac
done
HISTORY="${HISTORY:+$HISTORY;}$CHAIN_ID,$DONOR_PUBKEY,$STREAMER,$GROSS"

echo "== wait for ingest (timer runs every 60s; devnet finality ~30s)"
GOT=""
for _ in $(seq 1 40); do
    sleep 15
    GOT=$(reputation)
    echo "reputation($DONOR_PUBKEY -> $STREAMER) = $GOT / $EXPECTED_PAIR"
    [ "$GOT" = "$EXPECTED_PAIR" ] && break
done
[ "$GOT" = "$EXPECTED_PAIR" ] || { echo "FAIL: reputation never reached $EXPECTED_PAIR"; exit 1; }

echo "== exactly-once: two more timer rounds must change nothing"
sleep 130
GOT=$(reputation)
[ "$GOT" = "$EXPECTED_PAIR" ] || { echo "FAIL: book changed on idle rounds: $GOT"; exit 1; }

echo "== anomalies must be zero"
ANOMALIES=$(dfx canister call crown-index get_anomaly_count --query | tr -d '(_ )' | sed 's/:nat64//')
[ "$ANOMALIES" = "0" ] || { echo "FAIL: anomaly count = $ANOMALIES"; exit 1; }

echo "== reduce version"
dfx canister call crown-index get_reduce_version --query

echo "== offchain certificate verification against the replica root key"
CROWN_REPLICA_URL="http://127.0.0.1:$(dfx info webserver-port)" \
CROWN_INDEX_ID="$INDEX_ID" \
CROWN_E2E_SETTLEMENTS="$HISTORY" \
    cargo test -p crown-index --test certificate -- --ignored --nocapture

echo "e2e OK"
