#!/usr/bin/env bash
# E2e атрибуции: ветка признания №2 против живого devnet, оба шейпа
# конвенции (payout-table и stream). Никаких новых транзакций: клейм
# таблицы (2 получателя, 70/30) и два release потока уже лежат в чейне.
#   — каждый Settled эскроу попадает в книгу ДОНОРУ, по паре на получателя;
#   — несколько Settled из одной транзакции засчитываются все;
#   — аномалий ноль; сертификат сходится с независимым пересчётом.
#
# Usage: scripts/e2e-attribution.sh
set -euo pipefail
cd "$(dirname "$0")/.."

SOL_RPC_URL=${SOL_RPC_URL:-https://api.devnet.solana.com}

# Созвездие прогонов `flow` драйверов crown-factory (examples/devnet.rs,
# 2026-07-12): payout-table claim = 2 Settled в одной транзакции
# (70000 → A, 30000 → B); два stream release = ещё по паре тех же сумм.
SOL_DONOR=2b6JQquqQDsS8o3DFDiaxFLKTFMro1YrvVq7aimV4FzD
SOL_STREAMER_A=Gt381v8RqGQUX7vdRbC9NdZCzGuzk6ZUgcTDLfUnYdcJ
SOL_STREAMER_B=ByQ5SXVFXM1zJRg5vDztqs4ZdRdRSSBgvoWvMAw5Rgcx
SOL_GOAL_A=210000   # 3 × 70000
SOL_GOAL_B=90000    # 3 × 30000
# Первая транзакция созвездия в истории сплиттера — клейм payout-table.
SOL_SETTLE_TX=27doAqTfMMZZ3Ca73WGRAEhGLB2DRCQ1CqbWW5L7LUgGHg8zW417rdYpxWUfNUExi7eXt2MtCh8PKaXf6suAFCw6

export CC_wasm32_unknown_unknown="$PWD/scripts/wasm-cc.sh"
export AR_wasm32_unknown_unknown="${AR_WASM32:-$HOME/.cache/solana/v1.53/platform-tools/llvm/bin/llvm-ar}"
export CROWN_PROFILE=local

chain_value() { grep "^$1" config/testnet.toml | sed -n "$2p" | cut -d'=' -f2- | tr -d ' "[]'; }
SOL_SPLITTER=$(chain_value splitter 1)
SOL_USDC=$(chain_value usdc 1)
# Все пиннутые фабрики профиля, в синтаксис TOML-списка.
SOL_FACTORIES=$(chain_value factories 1 | sed 's/,/", "/g')

# Сид курсора: подпись сплиттера, идущая сразу ПЕРЕД первой транзой
# созвездия в истории (ингест возьмёт всё новее неё — ровно три транзы,
# шесть Settled).
SOL_SEED=$(curl -s "$SOL_RPC_URL" -X POST -H "Content-Type: application/json" -d "{
    \"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"getSignaturesForAddress\",
    \"params\":[\"$SOL_SPLITTER\", {\"limit\": 100}]}" | python3 -c "
import json, sys
sigs = [s['signature'] for s in json.load(sys.stdin)['result']]
print(sigs[sigs.index('$SOL_SETTLE_TX') + 1])")
echo "solana cursor seed: $SOL_SEED"

cat > config/local.toml <<EOF
# Generated by scripts/e2e-attribution.sh for the local run; never committed.
[[chain]]
id        = "solana-devnet"
source    = "Custom:$SOL_RPC_URL"
consensus = "equality"
splitter  = "$SOL_SPLITTER"
usdc      = "$SOL_USDC"
factories = ["$SOL_FACTORIES"]
EOF

echo "== canisters"
dfx stop >/dev/null 2>&1 || true
dfx start --clean --background
trap 'dfx stop >/dev/null 2>&1 || true' EXIT
dfx deploy sol_rpc
dfx deploy crown-index --argument "(opt record {
    sol_rpc = opt principal \"$(dfx canister id sol_rpc)\";
    cursor_seed = opt vec {
        record { \"solana-devnet\"; \"$SOL_SEED\" };
    } })"
INDEX_ID=$(dfx canister id crown-index)
dfx ledger fabricate-cycles --canister crown-index --t 100 >/dev/null

blob_b58() {
    python3 - "$1" <<'EOF'
import sys
A = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"
s = sys.argv[1]
n = 0
for c in s:
    n = n * 58 + A.index(c)
b = n.to_bytes((n.bit_length() + 7) // 8, "big")
b = b"\0" * (len(s) - len(s.lstrip("1"))) + b
print("".join(f"\\{x:02x}" for x in b))
EOF
}
reputation() { # payer_blob streamer_blob
    dfx canister call crown-index get_reputation "(\"solana-devnet\", blob \"$1\", blob \"$2\")" \
        --query | tr -d '(_ )' | sed 's/:nat//'
}

echo "== wait for ingest"
SOL_GOT_A=""
SOL_GOT_B=""
for _ in $(seq 1 25); do
    sleep 20
    SOL_GOT_A=$(reputation "$(blob_b58 $SOL_DONOR)" "$(blob_b58 $SOL_STREAMER_A)")
    SOL_GOT_B=$(reputation "$(blob_b58 $SOL_DONOR)" "$(blob_b58 $SOL_STREAMER_B)")
    echo "donor: A = $SOL_GOT_A / $SOL_GOAL_A, B = $SOL_GOT_B / $SOL_GOAL_B"
    [ "$SOL_GOT_A" = "$SOL_GOAL_A" ] && [ "$SOL_GOT_B" = "$SOL_GOAL_B" ] && break
done
[ "$SOL_GOT_A" = "$SOL_GOAL_A" ] && [ "$SOL_GOT_B" = "$SOL_GOAL_B" ] \
    || { echo "FAIL: settlements not attributed to donor"; exit 1; }

echo "== anomalies must be zero"
ANOMALIES=$(dfx canister call crown-index get_anomaly_count --query | tr -d '(_ )' | sed 's/:nat64//')
[ "$ANOMALIES" = "0" ] || { echo "FAIL: anomaly count = $ANOMALIES"; exit 1; }

echo "== certificate against the replica root key + independent recount"
CROWN_REPLICA_URL="http://127.0.0.1:$(dfx info webserver-port)" \
CROWN_INDEX_ID="$INDEX_ID" \
CROWN_E2E_SETTLEMENTS="solana-devnet,$SOL_DONOR,$SOL_STREAMER_A,$SOL_GOAL_A;solana-devnet,$SOL_DONOR,$SOL_STREAMER_B,$SOL_GOAL_B" \
    cargo test -p crown-index --test certificate -- --ignored --nocapture

echo "e2e attribution OK"
