#!/usr/bin/env bash
# S4 e2e (docs/build-plan.md): local replica + local EVM RPC canister against
# a local anvil chain carrying the real Splitter bytecode and a mock USDC.
#
# Usage: scripts/e2e-evm-local.sh [gross]
# Steps:
#   1. anvil with fast finality; deploy MockUSDC + Splitter, fund the donor,
#   2. deploy evm_rpc + crown-index (pinned to the local evm_rpc),
#   3. donate, mine past finality,
#   4. assert reputation, exactly-once, zero anomalies,
#   5. verify the certificate offchain against the replica root key.
set -euo pipefail
cd "$(dirname "$0")/.."

GROSS=${1:-1000000}
CHAIN_ID="eth-local"
RPC="http://127.0.0.1:8545"
FEE_BPS=300

export CC_wasm32_unknown_unknown="$PWD/scripts/wasm-cc.sh"
export AR_wasm32_unknown_unknown="${AR_WASM32:-$HOME/.cache/solana/v1.53/platform-tools/llvm/bin/llvm-ar}"
export CROWN_PROFILE=local

cleanup() {
    dfx stop >/dev/null 2>&1 || true
    [ -n "${ANVIL_PID:-}" ] && kill "$ANVIL_PID" 2>/dev/null || true
}
trap cleanup EXIT

echo "== anvil (finality lag of a couple of blocks)"
anvil --port 8545 --slots-in-an-epoch 1 >/dev/null 2>&1 &
ANVIL_PID=$!
sleep 2

# anvil's first two funded dev accounts: donor and streamer/treasury targets.
DONOR_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
DONOR=$(cast wallet address "$DONOR_KEY")
STREAMER=0x70997970C51812dc3A010C7d01b50e0d17dc79C8
TREASURY=0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC

echo "== contracts on anvil"
USDC=$(cd contracts/evm && forge create test/Splitter.t.sol:MockUSDC \
    --rpc-url "$RPC" --private-key "$DONOR_KEY" --broadcast --json | python3 -c "import json,sys; print(json.load(sys.stdin)['deployedTo'])")
SPLITTER=$(cd contracts/evm && forge create src/Splitter.sol:Splitter \
    --rpc-url "$RPC" --private-key "$DONOR_KEY" --broadcast --json \
    --constructor-args "$FEE_BPS" "$TREASURY" "$USDC" | python3 -c "import json,sys; print(json.load(sys.stdin)['deployedTo'])")
echo "usdc: $USDC  splitter: $SPLITTER"
cast send --rpc-url "$RPC" --private-key "$DONOR_KEY" "$USDC" "mint(address,uint256)" "$DONOR" 100000000 >/dev/null
cast send --rpc-url "$RPC" --private-key "$DONOR_KEY" "$USDC" "approve(address,uint256)" "$SPLITTER" 100000000 >/dev/null

cat > config/local.toml <<EOF
# Generated by scripts/e2e-evm-local.sh for the local run; never committed.
[[chain]]
id        = "$CHAIN_ID"
source    = "Custom:31337:$RPC"
consensus = "equality"
splitter  = "$SPLITTER"
usdc      = "$USDC"
EOF

echo "== canisters"
dfx stop >/dev/null 2>&1 || true
dfx start --clean --background
dfx deploy evm_rpc
dfx deploy crown-index --argument \
    "(opt record { sol_rpc = null; evm_rpc = opt principal \"$(dfx canister id evm_rpc)\"; cursor_seed = null })"
INDEX_ID=$(dfx canister id crown-index)
dfx ledger fabricate-cycles --canister crown-index --t 100 >/dev/null

echo "== donate $GROSS and mine past finality"
cast send --rpc-url "$RPC" --private-key "$DONOR_KEY" "$SPLITTER" "donate(address,uint256)" "$STREAMER" "$GROSS" >/dev/null
cast rpc --rpc-url "$RPC" anvil_mine 10 >/dev/null

blob() { # 0x-hex -> candid blob escapes
    python3 -c "import sys; print(''.join(f'\\\\{b:02x}' for b in bytes.fromhex(sys.argv[1][2:])))" "$1"
}
reputation() {
    dfx canister call crown-index get_reputation \
        "(\"$CHAIN_ID\", blob \"$(blob "$DONOR")\", blob \"$(blob "$STREAMER")\")" \
        --query | tr -d '(_ )' | sed 's/:nat//'
}

echo "== wait for ingest (timer runs every 60s)"
GOT=""
for _ in $(seq 1 20); do
    sleep 15
    GOT=$(reputation)
    echo "reputation($DONOR -> $STREAMER) = $GOT / $GROSS"
    [ "$GOT" = "$GROSS" ] && break
done
[ "$GOT" = "$GROSS" ] || { echo "FAIL: reputation never reached $GROSS"; exit 1; }

echo "== exactly-once: two more timer rounds must change nothing"
sleep 130
GOT=$(reputation)
[ "$GOT" = "$GROSS" ] || { echo "FAIL: book changed on idle rounds: $GOT"; exit 1; }

echo "== anomalies must be zero"
ANOMALIES=$(dfx canister call crown-index get_anomaly_count --query | tr -d '(_ )' | sed 's/:nat64//')
[ "$ANOMALIES" = "0" ] || { echo "FAIL: anomaly count = $ANOMALIES"; exit 1; }

echo "== offchain certificate verification against the replica root key"
CROWN_REPLICA_URL="http://127.0.0.1:$(dfx info webserver-port)" \
CROWN_INDEX_ID="$INDEX_ID" \
CROWN_E2E_SETTLEMENTS="$CHAIN_ID,$DONOR,$STREAMER,$GROSS" \
    cargo test -p crown-index --test certificate -- --ignored --nocapture

echo "e2e OK"
